"use client";
import {FormEvent,useEffect,useState} from "react";
const actions=[["Wave","wave hello"],["Wave both","wave with both arms"],["Bow","take a bow"],["Shrug","shrug"],["Point","point over there"],["Dance","let's dance"],["Sit / rest","sit down and rest"]];
const memeActions=[["Dab","dab"],["Flex","flex"],["Floss","floss"],["The Robot","do the robot"],["Mic drop","mic drop"],["Finger guns","finger guns"],["Aura farm","aura farm"],["Six seven","six seven gesture"],["NPC mode","npc mode"],["Facepalm","facepalm"],["Big win","victory pump"],["Side eye","side eye"]];
type Line={who:"you"|"bot";text:string};
function getSessionId(){let id=localStorage.getItem("meccanoid.session");if(!id){id=crypto.randomUUID();localStorage.setItem("meccanoid.session",id)}return id}
async function saveEvent(kind:"chat"|"command"|"error",role:"you"|"bot"|"system",message:string,latencyMs?:number){try{await fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:getSessionId(),kind,role,message,latencyMs})})}catch{/* Robot control must keep working if history storage is temporarily unavailable. */}}
export default function Home(){
 const [endpoint,setEndpoint]=useState(""),[draft,setDraft]=useState(""),[token,setToken]=useState(""),[tokenDraft,setTokenDraft]=useState("");
 const [message,setMessage]=useState(""),[mode,setMode]=useState<"idle"|"active"|"alert">("idle"),[latency,setLatency]=useState("—"),[busy,setBusy]=useState(false);
 const [lines,setLines]=useState<Line[]>([{who:"bot",text:"Chest core warm. Console ready."}]);
 useEffect(()=>{const e=localStorage.getItem("meccanoid.endpoint")||"",t=localStorage.getItem("meccanoid.token")||"";setEndpoint(e);setDraft(e);setToken(t);setTokenDraft(t);
  fetch(`/api/events?session=${encodeURIComponent(getSessionId())}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(Array.isArray(d.events)&&d.events.length)setLines(d.events.slice().reverse().map((x:{role:string;message:string})=>({who:x.role==="you"?"you":"bot",text:x.message}))) }).catch(()=>{})},[]);
 async function send(text:string,kind:"chat"|"command"="chat"){text=text.trim();if(!text||busy)return;setBusy(true);setMode("active");setLines(v=>[...v,{who:"you",text}]);void saveEvent(kind,"you",text);const t=performance.now();
  try{let reply;if(!endpoint){await new Promise(r=>setTimeout(r,450));reply=text.toLowerCase().includes("dance")?"Dance sequence queued in demo mode.":"Demo response received. Link your /chat endpoint for the real robot."}else{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({message:text})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||`HTTP ${r.status}`);reply=d.reply||"Command accepted."}const elapsed=Math.round(performance.now()-t);setLatency(`${elapsed}ms`);setLines(v=>[...v,{who:"bot",text:reply}]);void saveEvent(kind,"bot",reply,elapsed);setMode("idle")}catch(e){setMode("alert");const error=`Link error: ${e instanceof Error?e.message:"unknown error"}`;setLines(v=>[...v,{who:"bot",text:error}]);void saveEvent("error","system",error)}finally{setBusy(false)}}
 function submit(e:FormEvent){e.preventDefault();const text=message;setMessage("");void send(text)}
 function save(){const e=draft.trim();if(e&&!/^https?:\/\//i.test(e)){setMode("alert");return}setEndpoint(e);setToken(tokenDraft.trim());localStorage.setItem("meccanoid.endpoint",e);localStorage.setItem("meccanoid.token",tokenDraft.trim());setLines(v=>[...v,{who:"bot",text:e?"Backend link saved.":"Demo mode enabled."}]);setMode(e?"active":"idle")}
 return <main className={`console ${mode}`}><header><div className="brand"><b>MECCANOID</b> // CONSOLE</div><div className="unit">UNIT-01 · PERSONAL 2.0</div></header>
 <section className="hero"><button className="core" onClick={()=>setMode("active")} aria-label="Wake console"><span>{mode==="active"?"LINKED":mode==="alert"?"ATTENTION":"STANDBY"}</span><b>{mode.toUpperCase()}</b></button><p>Tap core to wake unit</p></section>
 <section className="telemetry"><div><small>MODE</small><b>{endpoint?"LIVE":"DEMO"}</b></div><div><small>LATENCY</small><b>{latency}</b></div><div><small>SERVOS</small><b>4 / 4</b></div></section>
 <section className="panel"><h2>Motor actions</h2><div className="actions">{actions.map(([l,p])=><button key={l} disabled={busy} onClick={()=>void send(p,"command")}><i/>{l}</button>)}</div></section>
 <section className="panel"><h2>Dance / meme moves</h2><div className="actions">{memeActions.map(([l,p])=><button key={l} disabled={busy} onClick={()=>void send(p,"command")}><i/>{l}</button>)}</div></section>
 <section className="panel mirrorCallout"><h2>Camera mirror</h2><p>Use a phone or laptop camera to generate an on-device arm wireframe and safely mirror four joint angles.</p><a href="/mirror">OPEN POSE MIRROR →</a></section>\n <section className="panel"><h2>Comms link</h2><div className="feed">{lines.map((l,i)=><p key={i} className={l.who}><b>{l.who==="you"?"YOU »":"BOT »"}</b> {l.text}</p>)}</div><form onSubmit={submit}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Say something to the robot…" aria-label="Message"/><button disabled={busy}>{busy?"WAIT":"SEND"}</button></form></section>
 <section className="panel"><h2>Link configuration</h2><label>Backend /chat endpoint<input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="https://your-backend.example.com/chat"/></label><label>Bearer token (optional)<input type="password" value={tokenDraft} onChange={e=>setTokenDraft(e.target.value)} placeholder="Stored only in this browser"/></label><button className="outline" onClick={save}>SAVE LINK SETTINGS</button><p className="note">No server keys are stored here. Link settings stay in this browser and are sent only to your endpoint.</p></section></main>
}