"use client";
import {useEffect,useRef,useState} from "react";
import {DrawingUtils,FilesetResolver,PoseLandmarker} from "@mediapipe/tasks-vision";
type Pose={right_shoulder:number;right_elbow:number;left_shoulder:number;left_elbow:number};
const MODEL="https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task";
const WASM="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm";
const clamp=(v:number,lo=15,hi=165)=>Math.max(lo,Math.min(hi,v));
function angle(a:{x:number;y:number},b:{x:number;y:number},c:{x:number;y:number}){const u={x:a.x-b.x,y:a.y-b.y},v={x:c.x-b.x,y:c.y-b.y},d=Math.hypot(u.x,u.y)*Math.hypot(v.x,v.y);return d?Math.acos(clamp((u.x*v.x+u.y*v.y)/d,-1,1))*180/Math.PI:90}
function arm(s:{x:number;y:number},e:{x:number;y:number},w:{x:number;y:number},h:{x:number;y:number}){return{shoulder:clamp(angle(h,s,e)),elbow:clamp(angle(s,e,w))}}
export default function MirrorPage(){
 const video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),stream=useRef<MediaStream|null>(null),tracker=useRef<PoseLandmarker|null>(null);
 const raf=useRef(0),running=useRef(false),sending=useRef(false),lastSent=useRef(0),smooth=useRef<Pose>({right_shoulder:90,right_elbow:90,left_shoulder:90,left_elbow:90});
 const [endpoint,setEndpoint]=useState(""),[token,setToken]=useState(""),[status,setStatus]=useState("Camera stopped");
 function stop(report=true){running.current=false;cancelAnimationFrame(raf.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(report)setStatus("Camera stopped — robot dead-man returns arms to rest.")}
 async function start(){stop(false);try{setStatus("Loading on-device pose tracker…");const vision=await FilesetResolver.forVisionTasks(WASM);tracker.current??=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL},runningMode:"VIDEO",numPoses:1,minPoseDetectionConfidence:.55,minTrackingConfidence:.55});stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});if(!video.current)return;video.current.srcObject=stream.current;await video.current.play();running.current=true;setStatus("Tracking locally. Only four joint angles leave this browser.");frame()}catch(e){stop(false);setStatus("Camera error: "+(e instanceof Error?e.message:"permission or model load failed"))}}
 function frame(){if(!running.current||!video.current||!canvas.current||!tracker.current)return;const v=video.current,c=canvas.current;if(v.videoWidth&&v.currentTime){c.width=v.videoWidth;c.height=v.videoHeight;const result=tracker.current.detectForVideo(v,performance.now()),ctx=c.getContext("2d");if(ctx){ctx.clearRect(0,0,c.width,c.height);const draw=new DrawingUtils(ctx);for(const points of result.landmarks){draw.drawConnectors(points,PoseLandmarker.POSE_CONNECTIONS,{color:"#4fd8e0",lineWidth:3});draw.drawLandmarks(points,{color:"#ffb020",radius:3})}}const p=result.landmarks[0];if(p&&[11,12,13,14,15,16,23,24].every(i=>(p[i].visibility??1)>.45)){const hl=arm(p[11],p[13],p[15],p[23]),hr=arm(p[12],p[14],p[16],p[24]),target:Pose={right_shoulder:hl.shoulder,right_elbow:hl.elbow,left_shoulder:hr.shoulder,left_elbow:hr.elbow};for(const k of Object.keys(target) as (keyof Pose)[])smooth.current[k]=.7*smooth.current[k]+.3*target[k];if(endpoint&&performance.now()-lastSent.current>=100&&!sending.current){lastSent.current=performance.now();sending.current=true;fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})},body:JSON.stringify({pose:smooth.current})}).then(async r=>{if(!r.ok&&r.status!==429)throw new Error((await r.json().catch(()=>({}))).error||"HTTP "+r.status)}).catch(e=>setStatus("Robot link error: "+(e instanceof Error?e.message:"request failed"))).finally(()=>{sending.current=false})}}}raf.current=requestAnimationFrame(frame)}
 useEffect(()=>{const chat=localStorage.getItem("meccanoid.endpoint")||"";setEndpoint(localStorage.getItem("meccanoid.mirrorEndpoint")||chat.replace(/\/chat\/?$/,"/mirror_pose"));setToken(localStorage.getItem("meccanoid.token")||"");return()=>{stop(false);tracker.current?.close()}},[]);
 function save(){localStorage.setItem("meccanoid.mirrorEndpoint",endpoint.trim());setEndpoint(endpoint.trim());setStatus(endpoint?"Mirror endpoint saved.":"Wireframe-only mode.");}
 return <main className="console mirror-console"><header><a href="/">← CONSOLE</a><div className="unit">POSE MIRROR</div></header><section className="panel"><h1>Camera arm mirror</h1><p className="note">Your phone or laptop draws a live wireframe and maps your shoulders and elbows to the robot. Video processing stays in the browser.</p><div className="camera-stage"><video ref={video} playsInline muted/><canvas ref={canvas}/></div><p className="mirror-status">{status}</p><div className="mirror-controls"><button onClick={()=>void start()}>START CAMERA</button><button className="outline" onClick={()=>stop()}>STOP (AUTO-REST)</button></div></section><section className="panel"><h2>Robot link</h2><label>Pi /mirror_pose endpoint<input value={endpoint} onChange={e=>setEndpoint(e.target.value.trim())} placeholder="https://your-pi.example.com/mirror_pose"/></label><label>Bearer token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Same DASHBOARD_TOKEN as /chat"/></label><button className="outline" onClick={save}>SAVE MIRROR LINK</button><p className="note">The Pi must set ENABLE_MIRROR_CONTROL=1 and MIRROR_ALLOWED_ORIGIN to this dashboard origin. HTTPS is required when this page is public.</p></section></main>
}